name: Rename All Clicks and Deploy Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    rename:
      name: Rename and Deploy Pages
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup ffmpeg
          uses: FedericoCarboni/setup-ffmpeg@v3
          id: setup-ffmpeg
        - name: Install Packages
          run: |
            python -m pip install ffmpeg
            python -m pip install pydub
        - name: Run Sounds Copier
          run: python ./.github/CopySoundsForRename.py
        - name: Run File Namer
          run: cd .github/FileNamer; python main.py
        - name: Copy Output to the Original Folder
          run: python .github/CopySoundsForRenamePT2.py
        - name: Update Repository
          run: |
            git config user.name "Sounds Updater"
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update Sounds (renames all multiple click files)" && git push || echo "Nothing to commit, there's no changes."
        - name: Get Click and Release files
          id: get-files
          run: |
            output="{\"e\": {"
            for dir in Meme/*/
            do
                dir=${dir%*/}
                output="${output}, \"${dir}\": {\"c\": ["
                for file in "Meme/$dir/Clicks/*"
                do
                    output="${output}, \"${file}\""
                done
                output="${output}], \"r\": ["
                for file in "Meme/$dir/Releases/*"
                do
                    output="${output}, \"${file}\""
                done
                output="${output}]}"
            done
            for dir in Useful/*/
            do
                dir=${dir%*/}
                output="${output}, \"${dir}\": {\"c\": ["
                for file in "Useful/$dir/Clicks/*"
                do
                    output="${output}, \"${file}\""
                done
                output="${output}], \"r\": ["
                for file in "Useful/$dir/Releases/*"
                do
                    output="$output, \"${file}\""
                done
                output="$output]}"
            done
            output="$output}"
            echo "files=\"${output}\"" >> "$GITHUB_OUTPUT"
        - name: Run json creator
          run: cd .github/JsonCreator/; python main.py
          env:
            ALL_FILES: ${{ steps.get-files.outputs.files }}
        - name: Compress Into Zip for pages
          run: |
            for dir in Meme/*/
            do
                dir=${dir%*/}
                7z a ${dir}.zip ${dir}
            done
            for dir in Useful/*/
            do
                dir=${dir%*/}
                7z a ${dir}.zip ${dir}
            done
        - name: Setup Pages
          uses: actions/configure-pages@v4
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: '.'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
    