name: Rename All Clicks

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
    rename:
      name: Rename Click Sounds
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup ffmpeg
          uses: FedericoCarboni/setup-ffmpeg@v3
          id: setup-ffmpeg
        - name: Install Packages
          run: |
            python -m pip install ffmpeg
            python -m pip install pydub
        - name: Run Sounds Copier
          run: python ./.github/CopySoundsForRename.py
        - name: Run File Namer
          run: cd .github/FileNamer; python main.py
        - name: Copy Output to the Original Folder
          run: python .github/CopySoundsForRenamePT2.py
        - name: Update Repository
          run: |
            git config user.name "Sounds Updater"
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update Sounds (renames all multiple click files)" && git push || echo "Nothing to commit, there's no changes."
